### ISSUE TITLE
Exceptions

### ISSUE THREAD

**Issue by Jediworm** [minepy/mictools#8]
Hello, I'm following the docker install and usage instructions:

docker pull minepy/mictools
docker run --rm -t -i -v /Users/will/Documents/mictools:/mictools -w /mictools minepy/mictools /bin/bash

But when running any commands, I get this below message:

raceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 655, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 963, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 854, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (numpy 1.12.1 (/usr/lib/python3/dist-packages), Requirement.parse('numpy>=1.14'), {'statsmodels'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/mictools", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3019, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 657, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 670, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 854, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (numpy 1.12.1 (/usr/lib/python3/dist-packages), Requirement.parse('numpy>=1.14'), {'statsmodels'})

Is this a problem with the python version? I am running 2.7.16, but I thought the docker image included python3?

Thanks for your help!

**Comment by davidealbanese** [comment]
Fixed in https://github.com/minepy/mictools/commit/cb7908d03d87c3a764b9fa520217fde6df2acb12.
